### ISSUE TITLE
Tag 0.0.1 does not include registration.php file

### ISSUE THREAD

**Issue by thanasisgalanis** [astorm/magento2-tutorial-objectmanager2#2]
In [this article](http://alanstorm.com/magento2_dependency_injection_2015/) you have a link to the module's ["latest release"](https://github.com/astorm/magento2-tutorial-objectmanager2/releases) page. However tag 0.0.1 (the latest realese so far), does not include registration.php file.

**Comment by astorm** [comment]
Thank you @sakisplus!  I hope the missing registration.php didn't cost you too much time. 

We've just created a new tag (`0.0.2`) with the latest release.  If you find any other tutorial sample modules with this problem please let us know.

**Comment by thanasisgalanis** [comment]
Thank you @astorm, for your super fast response and of course for your great articles.
